name: Sync Site Data

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:      # allows manual runs

jobs:
  update-site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout portfolio repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # we’ll push manually later
          fetch-depth: 0

      - name: Clone Garmin data repo
        run: |
          git clone https://.:${{ secrets.GITHUB_TOKEN }}@github.com/RobinVH/GarminData.git garmin-temp

      - name: Copy output to site folder
        run: |
          mkdir -p GarminData
          cp -r garmin-temp/GarminData/output/* garmin/

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add garmin
          git commit -m "Update Garmin data $(date)" || echo "No changes"
          git push
